application: davidadlersapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style
  static_dir: static/style
- url: /5grid-style
  static_dir: static/style/5grid-style
- url: /images
  static_dir: static/images
- url: /files
  static_dir: static/files
- url: /js
  static_dir: static/js
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: favicon\.ico

- url: /.*
  script: main.app



libraries:
- name: jinja2
  version: latest
