(function(){function f(d){this.t={};this.tick=function(d,f,l){l=void 0!=l?l:(new Date).getTime();this.t[d]=[l,f]};this.tick("start",null,d)}var d=new f;window.jstiming={Timer:f,load:d};if(window.performance&&window.performance.timing){var d=window.performance.timing,p=window.jstiming.load,m=d.navigationStart,d=d.responseStart;0<m&&d>=m&&(p.tick("_wtsrt",void 0,m),p.tick("wtsrt_","_wtsrt",d),p.tick("tbsd_","wtsrt_"))}try{d=null,window.chrome&&window.chrome.csi&&(d=Math.floor(window.chrome.csi().pageT),
p&&0<m&&(p.tick("_tbnd",void 0,window.chrome.csi().startE),p.tick("tbnd_","_tbnd",m))),null==d&&window.gtbExternal&&(d=window.gtbExternal.pageT()),null==d&&window.external&&(d=window.external.pageT,p&&0<m&&(p.tick("_tbnd",void 0,window.external.startE),p.tick("tbnd_","_tbnd",m))),d&&(window.jstiming.pt=d)}catch(C){}})();/*

 MIT License
 Copyright (c) 2009?2011
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.

 BSD License
 Copyright (c) 2011
 All rights reserved.
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
 Redistributions of source code must retain the above copyright
 notice, this list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright
 notice, this list of conditions and the following disclaimer in the
 documentation and/or other materials provided with the distribution.
 Neither the name of the Organization nor the
 names of its contributors may be used to endorse or promote products
 derived from this software without specific prior written permission.
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDER BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
window.Modernizr=function(f,d,p){function m(a,b){return typeof a===b}function C(a,b){for(var k in a){var g=a[k];if(!~(""+g).indexOf("-")&&s[g]!==p)return"pfx"==b?g:!0}return!1}function r(a,b,k){var g=a.charAt(0).toUpperCase()+a.slice(1),d=(a+" "+K.join(g+" ")+g).split(" "),c;if(m(b,"string")||m(b,"undefined"))c=C(d,b);else{d=(a+" "+L.join(g+" ")+g).split(" ");e:{a=d;for(c in a)if(g=b[a[c]],g!==p){c=!1===k?a[c]:m(g,"function")?g.bind(k||b):g;break e}c=!1}}return c}function O(){l.input=function(a){for(var b=
0,k=a.length;b<k;b++)D[a[b]]=a[b]in t;return D.list&&(D.list=!!d.createElement("datalist")&&!!f.HTMLDataListElement),D}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));l.inputtypes=function(a){for(var b=0,k,g,c,e=a.length;b<e;b++)t.setAttribute("type",g=a[b]),(k="text"!==t.type)&&(t.value=E,t.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(g)&&t.style.WebkitAppearance!==p?(v.appendChild(t),c=d.defaultView,k=c.getComputedStyle&&"textfield"!==
c.getComputedStyle(t,null).WebkitAppearance&&0!==t.offsetHeight,v.removeChild(t)):/^(search|tel)$/.test(g)||(/^(url|email)$/.test(g)?k=t.checkValidity&&!1===t.checkValidity():k=t.value!=E)),M[a[b]]=!!k;return M}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var B="2.6.2",l={},N=!0,v=d.documentElement,n="modernizr",e=d.createElement(n),s=e.style,t=d.createElement("input"),E=":)",F={}.toString,G=" -webkit- -moz- -o- -ms- ".split(" "),z="Webkit Moz O ms",
K=z.split(" "),L=z.toLowerCase().split(" "),J={svg:"http://www.w3.org/2000/svg"},e={},M={},D={},z=[],w=z.slice,H,A=function(a,b,k,g){var c,e,q,l,h=d.createElement("div"),f=d.body,m=f||d.createElement("body");if(parseInt(k,10))for(;k--;)q=d.createElement("div"),q.id=g?g[k]:n+(k+1),h.appendChild(q);return c=['&#173;<style id="s',n,'">',a,"</style>"].join(""),h.id=n,(f?h:m).innerHTML+=c,m.appendChild(h),f||(m.style.background="",m.style.overflow="hidden",l=v.style.overflow,v.style.overflow="hidden",
v.appendChild(m)),e=b(h,a),f?h.parentNode.removeChild(h):(m.parentNode.removeChild(m),v.style.overflow=l),!!e},x=function(a){var b=f.matchMedia||f.msMatchMedia;if(b)return b(a).matches;var k;return A("@media "+a+" { #"+n+" { position: absolute; } }",function(a){k="absolute"==(f.getComputedStyle?getComputedStyle(a,null):a.currentStyle).position}),k},c=function(){function a(a,g){g=g||d.createElement(b[a]||"div");a="on"+a;var c=a in g;return c||(g.setAttribute||(g=d.createElement("div")),g.setAttribute&&
g.removeAttribute&&(g.setAttribute(a,""),c=m(g[a],"function"),m(g[a],"undefined")||(g[a]=p),g.removeAttribute(a))),c}var b={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return a}(),q={}.hasOwnProperty,y;!m(q,"undefined")&&!m(q.call,"undefined")?y=function(a,b){return q.call(a,b)}:y=function(a,b){return b in a&&m(a.constructor.prototype[b],"undefined")};Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError;
var c=w.call(arguments,1),g=function(){if(this instanceof g){var d=function(){};d.prototype=b.prototype;var d=new d,e=b.apply(d,c.concat(w.call(arguments)));return Object(e)===e?e:d}return b.apply(a,c.concat(w.call(arguments)))};return g});e.flexbox=function(){return r("flexWrap")};e.flexboxlegacy=function(){return r("boxDirection")};e.canvas=function(){var a=d.createElement("canvas");return!!a.getContext&&!!a.getContext("2d")};e.canvastext=function(){return!!l.canvas&&!!m(d.createElement("canvas").getContext("2d").fillText,
"function")};e.webgl=function(){return!!f.WebGLRenderingContext};e.touch=function(){var a;return"ontouchstart"in f||f.DocumentTouch&&d instanceof DocumentTouch?a=!0:A(["@media (",G.join("touch-enabled),("),n,"){#modernizr{top:9px;position:absolute}}"].join(""),function(b){a=9===b.offsetTop}),a};e.geolocation=function(){return"geolocation"in navigator};e.postmessage=function(){return!!f.postMessage};e.websqldatabase=function(){return!!f.openDatabase};e.indexedDB=function(){return!!r("indexedDB",f)};
e.hashchange=function(){return c("hashchange",f)&&(d.documentMode===p||7<d.documentMode)};e.history=function(){return!!f.history&&!!history.pushState};e.draganddrop=function(){var a=d.createElement("div");return"draggable"in a||"ondragstart"in a&&"ondrop"in a};e.websockets=function(){return"WebSocket"in f||"MozWebSocket"in f};e.rgba=function(){var a;s.cssText="background-color:rgba(150,255,150,.5)";a=void 0;return!!~(""+s.backgroundColor).indexOf("rgba")};e.hsla=function(){var a;s.cssText="background-color:hsla(120,40%,100%,.5)";
a=void 0;return!!~(""+s.backgroundColor).indexOf("rgba")||!!~(""+s.backgroundColor).indexOf("hsla")};e.multiplebgs=function(){var a;s.cssText="background:url(https://),url(https://),red url(https://)";a=void 0;return/(url\s*\(.*?){3}/.test(s.background)};e.backgroundsize=function(){return r("backgroundSize")};e.borderimage=function(){return r("borderImage")};e.borderradius=function(){return r("borderRadius")};e.boxshadow=function(){return r("boxShadow")};e.textshadow=function(){return""===d.createElement("div").style.textShadow};
e.opacity=function(){var a;a=G.join("opacity:.55;")+"";s.cssText=a;a=void 0;return/^0.55$/.test(s.opacity)};e.cssanimations=function(){return r("animationName")};e.csscolumns=function(){return r("columnCount")};e.cssgradients=function(){var a="background-image:",b="gradient(linear,left top,right bottom,from(#9f9),to(white));",c="linear-gradient(left top,#9f9, white);",a=(a+["-webkit-",""].join(b+a)+G.join(c+a)).slice(0,-a.length);s.cssText=a;a=void 0;return!!~(""+s.backgroundImage).indexOf("gradient")};
e.cssreflections=function(){return r("boxReflect")};e.csstransforms=function(){return!!r("transform")};e.csstransforms3d=function(){var a=!!r("perspective");return a&&"webkitPerspective"in v.style&&A("@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px;}}",function(b){a=9===b.offsetLeft&&3===b.offsetHeight}),a};e.csstransitions=function(){return r("transition")};e.fontface=function(){var a;return A('@font-face {font-family:"font";src:url("https://")}',function(b,
c){var g=d.getElementById("smodernizr"),g=(g=g.sheet||g.styleSheet)?g.cssRules&&g.cssRules[0]?g.cssRules[0].cssText:g.cssText||"":"";a=/src/i.test(g)&&0===g.indexOf(c.split(" ")[0])}),a};e.generatedcontent=function(){var a;return A(["#",n,"{font:0/0 a}#",n,':after{content:"',E,'";visibility:hidden;font:3px/1 a}'].join(""),function(b){a=3<=b.offsetHeight}),a};e.video=function(){var a=d.createElement("video"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,
""),b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,"")}catch(c){}return b};e.audio=function(){var a=d.createElement("audio"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,""),b.mp3=a.canPlayType("audio/mpeg;").replace(/^no$/,""),b.wav=a.canPlayType('audio/wav; codecs="1"').replace(/^no$/,""),b.m4a=(a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")).replace(/^no$/,
"")}catch(c){}return b};e.localstorage=function(){try{return localStorage.setItem(n,n),localStorage.removeItem(n),!0}catch(a){return!1}};e.sessionstorage=function(){try{return sessionStorage.setItem(n,n),sessionStorage.removeItem(n),!0}catch(a){return!1}};e.webworkers=function(){return!!f.Worker};e.applicationcache=function(){return!!f.applicationCache};e.svg=function(){return!!d.createElementNS&&!!d.createElementNS(J.svg,"svg").createSVGRect};e.inlinesvg=function(){var a=d.createElement("div");return a.innerHTML=
"<svg/>",(a.firstChild&&a.firstChild.namespaceURI)==J.svg};e.smil=function(){return!!d.createElementNS&&/SVGAnimate/.test(F.call(d.createElementNS(J.svg,"animate")))};e.svgclippaths=function(){return!!d.createElementNS&&/SVGClipPath/.test(F.call(d.createElementNS(J.svg,"clipPath")))};for(var I in e)y(e,I)&&(H=I.toLowerCase(),l[H]=e[I](),z.push((l[H]?"":"no-")+H));l.input||O();l.addTest=function(a,b){if("object"==typeof a)for(var c in a)y(a,c)&&l.addTest(c,a[c]);else{a=a.toLowerCase();if(l[a]!==p)return l;
b="function"==typeof b?b():b;"undefined"!=typeof N&&N&&(v.className+=" "+(b?"":"no-")+a);l[a]=b}return l};s.cssText="";return e=t=null,function(a,b){function c(){var a=p.elements;return"string"==typeof a?a.split(" "):a}function g(a){var b=s[a[r]];return b||(b={},I++,a[r]=I,s[I]=b),b}function d(a,c,e){c||(c=b);if(y)return c.createElement(a);e||(e=g(c));var h;return e.cache[a]?h=e.cache[a].cloneNode():m.test(a)?h=(e.cache[a]=e.createElem(a)).cloneNode():h=e.createElem(a),h.canHaveChildren&&!l.test(a)?
e.frag.appendChild(h):h}function e(a,d){a||(a=b);if(y)return a.createDocumentFragment();d=d||g(a);for(var h=d.frag.cloneNode(),q=0,f=c(),l=f.length;q<l;q++)h.createElement(f[q]);return h}function q(a,b){b.cache||(b.cache={},b.createElem=a.createElement,b.createFrag=a.createDocumentFragment,b.frag=b.createFrag());a.createElement=function(c){return p.shivMethods?d(c,a,b):b.createElem(c)};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+
c().join().replace(/\w+/g,function(a){return b.createElem(a),b.frag.createElement(a),'c("'+a+'")'})+");return n}")(p,b.frag)}function f(a){a||(a=b);var c=g(a);if(p.shivCSS&&!n&&!c.hasCSS){var d=c,e,h=a;e=h.createElement("p");h=h.getElementsByTagName("head")[0]||h.documentElement;e=(e.innerHTML="x<style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>",h.insertBefore(e.lastChild,h.firstChild));d.hasCSS=!!e}return y||q(a,c),a}var h=
a.html5||{},l=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,m=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,n,r="_html5shiv",I=0,s={},y;(function(){try{var a=b.createElement("a");a.innerHTML="<xyz></xyz>";n="hidden"in a;var c;if(!(c=1==a.childNodes.length)){b.createElement("a");var d=b.createDocumentFragment();c="undefined"==typeof d.cloneNode||"undefined"==typeof d.createDocumentFragment||"undefined"==typeof d.createElement}y=
c}catch(g){y=n=!0}})();var p={elements:h.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:!1!==h.shivCSS,supportsUnknownElements:y,shivMethods:!1!==h.shivMethods,type:"default",shivDocument:f,createElement:d,createDocumentFragment:e};a.html5=p;f(b)}(this,d),l._version=B,l._prefixes=G,l._domPrefixes=L,l._cssomPrefixes=K,l.mq=x,l.hasEvent=c,l.testProp=function(a){return C([a])},
l.testAllProps=r,l.testStyles=A,l.prefixed=function(a,b,c){return b?r(a,b,c):r(a,"pfx")},v.className=v.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(N?" js "+z.join(" "):""),l}(this,this.document);
(function(f,d,p){function m(c){return"[object Function]"==t.call(c)}function C(c){return"string"==typeof c}function r(){}function O(c){return!c||"loaded"==c||"complete"==c||"uninitialized"==c}function B(){var c=E.shift();F=1;c?c.t?e(function(){("c"==c.t?x.injectCss:x.injectJs)(c.s,0,c.a,c.x,c.e,1)},0):(c(),B()):F=0}function l(c,q,f,l,a,b,k){function g(a){if(!m&&O(u.readyState)&&(r.r=m=1,!F&&B(),u.onload=u.onreadystatechange=null,a)){"img"!=c&&e(function(){K.removeChild(u)},50);for(var b in w[q])w[q].hasOwnProperty(b)&&
w[q][b].onload()}}k=k||x.errorTimeout;var u=d.createElement(c),m=0,n=0,r={t:f,s:q,e:a,a:b,x:k};1===w[q]&&(n=1,w[q]=[]);"object"==c?u.data=q:(u.src=q,u.type=c);u.width=u.height="0";u.onerror=u.onload=u.onreadystatechange=function(){g.call(this,n)};E.splice(l,0,r);"img"!=c&&(n||2===w[q]?(K.insertBefore(u,z?null:s),e(g,k)):w[q].push(u))}function N(c,d,e,f,a){return F=0,d=d||"j",C(c)?l("c"==d?J:L,c,d,this.i++,e,f,a):(E.splice(this.i++,0,c),1==E.length&&B()),this}function v(){var c=x;return c.loader={load:N,
i:0},c}var n=d.documentElement,e=f.setTimeout,s=d.getElementsByTagName("script")[0],t={}.toString,E=[],F=0,G="MozAppearance"in n.style,z=G&&!!d.createRange().compareNode,K=z?n:s.parentNode,n=f.opera&&"[object Opera]"==t.call(f.opera),n=!!d.attachEvent&&!n,L=G?"object":n?"script":"img",J=n?"script":L,M=Array.isArray||function(c){return"[object Array]"==t.call(c)},D=[],w={},H={timeout:function(c,d){return d.length&&(c.timeout=d[0]),c}},A,x;x=function(c){function d(a){a=a.split("!");var b=D.length,c=
a.pop(),e=a.length,c={url:c,origUrl:c,prefixes:a},f,h,k;for(h=0;h<e;h++)k=a[h].split("="),(f=H[k.shift()])&&(c=f(c,k));for(h=0;h<b;h++)c=D[h](c);return c}function e(a,b,c,f,k){var h=d(a),l=h.autoCallback;h.url.split(".").pop().split("?").shift();h.bypass||(b&&(b=m(b)?b:b[a]||b[f]||b[a.split("/").pop().split("?")[0]]),h.instead?h.instead(a,b,c,f,k):(w[h.url]?h.noexec=!0:w[h.url]=1,c.load(h.url,h.forceCSS||!h.forceJS&&"css"==h.url.split(".").pop().split("?").shift()?"c":p,h.noexec,h.attrs,h.timeout),
(m(b)||m(l))&&c.load(function(){v();b&&b(h.origUrl,k,f);l&&l(h.origUrl,k,f);w[h.url]=2})))}function f(a,b){function c(a,g){if(a)if(C(a))g||(h=function(){var a=[].slice.call(arguments);l.apply(this,a);q()}),e(a,h,b,0,d);else{if(Object(a)===a)for(p in n=function(){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}(),a)a.hasOwnProperty(p)&&(!g&&!--n&&(m(h)?h=function(){var a=[].slice.call(arguments);l.apply(this,a);q()}:h[p]=function(a){return function(){var b=[].slice.call(arguments);a&&a.apply(this,
b);q()}}(l[p])),e(a[p],h,b,p,d))}else!g&&q()}var d=!!a.test,k=a.load||a.both,h=a.callback||r,l=h,q=a.complete||r,n,p;c(d?a.yep:a.nope,!!k);k&&c(k)}var a,b,k=this.yepnope.loader;if(C(c))e(c,0,k,0);else if(M(c))for(a=0;a<c.length;a++)b=c[a],C(b)?e(b,0,k,0):M(b)?x(b):Object(b)===b&&f(b,k);else Object(c)===c&&f(c,k)};x.addPrefix=function(c,d){H[c]=d};x.addFilter=function(c){D.push(c)};x.errorTimeout=1E4;null==d.readyState&&d.addEventListener&&(d.readyState="loading",d.addEventListener("DOMContentLoaded",
A=function(){d.removeEventListener("DOMContentLoaded",A,0);d.readyState="complete"},0));f.yepnope=v();f.yepnope.executeStack=B;f.yepnope.injectJs=function(c,f,l,m,a,b){var k=d.createElement("script"),g,n;m=m||x.errorTimeout;k.src=c;for(n in l)k.setAttribute(n,l[n]);f=b?B:f||r;k.onreadystatechange=k.onload=function(){!g&&O(k.readyState)&&(g=1,f(),k.onload=k.onreadystatechange=null)};e(function(){g||(g=1,f(1))},m);a?k.onload():s.parentNode.insertBefore(k,s)};f.yepnope.injectCss=function(c,f,l,m,a,b){m=
d.createElement("link");var k;f=b?B:f||r;m.href=c;m.rel="stylesheet";m.type="text/css";for(k in l)m.setAttribute(k,l[k]);a||(s.parentNode.insertBefore(m,s),e(f,0))}})(this,document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};
